### PR TITLE
Remove t.is and t.not from enhanced patterns

### PR DESCRIPTION
**Pull request by vadimdemedes**
Somehow forgot to remove them before landing magic-assert. Needed to produce this:

screen shot 2017-02-04 at 12 34 02 am

instead of this:

screen shot 2017-02-04 at 12 34 14 am

### CODE REVIEW

**Comment by novemberborn** [comment]
I think this should've been `3.0.0` release. And https://github.com/avajs/ava/commit/154215df51fb1fbe9f5f5ca2f76e00b46d30c7d3 should list that as its minimum version (or at least `2.0.1`).

Not quite sure what happens if somebody has AVA `0.18.0` with version `2.0.1` of this preset.

**Comment by vadimdemedes** [comment]
I didn't make it a major release on purpose, so that all new AVA `0.18.0` installations would pick up `2.0.1` of this preset (since semver covers it).

**Comment by novemberborn** [comment]
Yes, though does that work as expected without the corresponding change in https://github.com/avajs/ava/commit/154215df51fb1fbe9f5f5ca2f76e00b46d30c7d3?

I think generally we should bump the versions in AVA, e.g. with https://github.com/avajs/pretty-format/releases/tag/v1.0.2.

**Comment by sindresorhus** [comment]
> I think this should've been 3.0.0 release.

You could probably argue either way. It doesn't really break anything though. It only slightly changes the output, which in AVA is really a bug fix.

> And avajs/ava@154215d should list that as its minimum version (or at least 2.0.1).

I agree. Generally if you need a new feature in the release, even if it's covered by semver, you should ensure it can never be lower. That could happen if the dependency tree has multiple versions of it.

**Comment by vadimdemedes** [comment]
> Yes, though does that work as expected without the corresponding change in avajs/ava@154215d?

@novemberborn No, I don't think so. I think you were right initially, it should've been `3.0.0`. Will know next time!

**Pull request merged**
